using System;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace AppMinhaBahia.Migrations
{
    public partial class CriandoEntidadesDoZero : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Cidades",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Nome = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Cidades", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Intervencao",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Descricao = table.Column<string>(nullable: true),
                    Data = table.Column<DateTime>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Intervencao", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Usuarios",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    NomeCompleto = table.Column<string>(maxLength: 50, nullable: false),
                    CPF = table.Column<string>(nullable: false),
                    CidadeId = table.Column<int>(nullable: true),
                    Senha = table.Column<string>(maxLength: 50, nullable: false),
                    Discriminator = table.Column<string>(nullable: false),
                    SetorId = table.Column<int>(nullable: true),
                    Disponivel = table.Column<bool>(nullable: true),
                    IntervencaoId = table.Column<int>(nullable: true),
                    UFId = table.Column<int>(nullable: true),
                    VerbaMunicipal = table.Column<double>(nullable: true),
                    SalarioMedioPorFuncionario = table.Column<double>(nullable: true),
                    NomeSetor = table.Column<string>(nullable: true),
                    Verba = table.Column<double>(nullable: true),
                    PrefeituraId = table.Column<int>(nullable: true),
                    NomeUF = table.Column<string>(nullable: true),
                    VerbaEstadual = table.Column<double>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Usuarios", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Usuarios_Intervencao_IntervencaoId",
                        column: x => x.IntervencaoId,
                        principalTable: "Intervencao",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Usuarios_Usuarios_SetorId",
                        column: x => x.SetorId,
                        principalTable: "Usuarios",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Usuarios_Usuarios_UFId",
                        column: x => x.UFId,
                        principalTable: "Usuarios",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Usuarios_Usuarios_PrefeituraId",
                        column: x => x.PrefeituraId,
                        principalTable: "Usuarios",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Usuarios_Cidades_CidadeId",
                        column: x => x.CidadeId,
                        principalTable: "Cidades",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "Ocorrencias",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn),
                    Tipo = table.Column<string>(maxLength: 50, nullable: false),
                    Descricao = table.Column<string>(maxLength: 1000, nullable: false),
                    UsuarioId = table.Column<int>(nullable: false),
                    LocalEspecifico = table.Column<string>(nullable: false),
                    Custo = table.Column<double>(nullable: true),
                    Funcionarios = table.Column<int>(nullable: true),
                    Data = table.Column<DateTime>(nullable: false),
                    IntervencaoId = table.Column<int>(nullable: true),
                    PrefeituraId = table.Column<int>(nullable: false),
                    Status = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Ocorrencias", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Ocorrencias_Intervencao_IntervencaoId",
                        column: x => x.IntervencaoId,
                        principalTable: "Intervencao",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_Ocorrencias_Usuarios_PrefeituraId",
                        column: x => x.PrefeituraId,
                        principalTable: "Usuarios",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Ocorrencias_Usuarios_UsuarioId",
                        column: x => x.UsuarioId,
                        principalTable: "Usuarios",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "Requisicao",
                columns: table => new
                {
                    SetorId = table.Column<int>(nullable: false),
                    PrefeituraId = table.Column<int>(nullable: false),
                    Id = table.Column<int>(nullable: false),
                    Tipo = table.Column<string>(nullable: true),
                    Data = table.Column<DateTime>(nullable: false),
                    Verba = table.Column<double>(nullable: true),
                    Funcionarios = table.Column<int>(nullable: true),
                    Status = table.Column<string>(nullable: true),
                    UFAdminId = table.Column<int>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Requisicao", x => new { x.SetorId, x.PrefeituraId });
                    table.ForeignKey(
                        name: "FK_Requisicao_Usuarios_PrefeituraId",
                        column: x => x.PrefeituraId,
                        principalTable: "Usuarios",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Requisicao_Usuarios_SetorId",
                        column: x => x.SetorId,
                        principalTable: "Usuarios",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_Requisicao_Usuarios_UFAdminId",
                        column: x => x.UFAdminId,
                        principalTable: "Usuarios",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.InsertData(
                table: "Cidades",
                columns: new[] { "Id", "Nome" },
                values: new object[,]
                {
                    { 1, "Abaíra" },
                    { 564, "Mutuípe" },
                    { 565, "Nazaré" },
                    { 566, "Nilo Peçanha" },
                    { 567, "São Benedito" },
                    { 568, "Nordestina" },
                    { 569, "Nova Canaã" },
                    { 570, "Itajaí" },
                    { 571, "Nova Fátima" },
                    { 572, "Nova Ibiá" },
                    { 573, "Nova Itarana" },
                    { 563, "Itaporã" },
                    { 574, "Nova Redenção" },
                    { 576, "Nova Viçosa" },
                    { 577, "Argolo" },
                    { 578, "Helvécia" },
                    { 579, "Posto da Mata" },
                    { 580, "Novo Horizonte" },
                    { 581, "Brejo Luiza de Brito" },
                    { 582, "Remédios" },
                    { 583, "Novo Triunfo" },
                    { 584, "Olindina" },
                    { 585, "Oliveira dos Brejinhos" },
                    { 575, "Nova Soure" },
                    { 562, "Muritiba" },
                    { 561, "Muquém do São Francisco" },
                    { 560, "Onha" },
                    { 537, "Morro do Chapéu" },
                    { 538, "Camirim" },
                    { 539, "Dias Coelho" },
                    { 540, "Duas Barras do Morro" },
                    { 541, "Icó" },
                    { 542, "Tamboril" },
                    { 543, "Ventura" },
                    { 544, "Mortugaba" },
                    { 545, "Mucugê" },
                    { 546, "Guiné" },
                    { 547, "João Correia" },
                    { 548, "Mucuri" },
                    { 549, "Ibiranhém" },
                    { 550, "Itabatã" },
                    { 551, "Taquarinha" },
                    { 552, "Mulungu do Morro" },
                    { 553, "Canudos" },
                    { 554, "Várzea do Cerco" },
                    { 555, "Mundo Novo" },
                    { 556, "Alto Bonito" },
                    { 557, "Ibiaporã" },
                    { 558, "Indaí" },
                    { 559, "Muniz Ferreira" },
                    { 586, "Bom Sossego" },
                    { 587, "Ipuçaba" },
                    { 588, "Ouriçangas" },
                    { 589, "Ourolândia" },
                    { 617, "Pindobaçu" },
                    { 618, "Bananeiras" },
                    { 619, "Carnaíba de Baixo" },
                    { 620, "Várzea Grande" },
                    { 621, "Pintadas" },
                    { 622, "Piraí do Norte" },
                    { 623, "Piripá" },
                    { 624, "Piritiba" },
                    { 625, "França" },
                    { 626, "Largo" },
                    { 627, "Porto Feliz" },
                    { 628, "Planaltino" },
                    { 629, "Ibitiguira" },
                    { 630, "Nova Itaípe" },
                    { 631, "Planalto" },
                    { 632, "Lucaia" },
                    { 633, "Poções" },
                    { 634, "Pojuca" },
                    { 635, "Miranga" },
                    { 636, "Ponto Novo" },
                    { 637, "Porto Seguro" },
                    { 638, "Arraial D\"Ajuda" },
                    { 639, "Caraíva" },
                    { 616, "Guirapá" },
                    { 536, "Quixaba" },
                    { 615, "Pindaí" },
                    { 613, "Brejo da Serra" },
                    { 590, "Alagadiço" },
                    { 591, "Palmas de Monte Alto" },
                    { 592, "Espraiado" },
                    { 593, "Pinga Fogo" },
                    { 594, "Rancho das Mães" },
                    { 595, "Palmeiras" },
                    { 596, "Caeté-Açu" },
                    { 597, "Paramirim" },
                    { 598, "Canabravinha" },
                    { 599, "Paratinga" },
                    { 600, "Águas do Paulista" },
                    { 601, "Paripiranga" },
                    { 602, "Conceição de Campinas" },
                    { 603, "Pau Brasil" },
                    { 604, "Paulo Afonso" },
                    { 605, "Pé de Serra" },
                    { 606, "Pedrão" },
                    { 607, "Pedro Alexandre" },
                    { 608, "Piatã" },
                    { 609, "Cabrália" },
                    { 610, "Inúbia" },
                    { 611, "Pilão Arcado" },
                    { 612, "Baluarte" },
                    { 614, "Saldanha" },
                    { 640, "Vale Verde" },
                    { 535, "Morpará" },
                    { 533, "Mirante" },
                    { 457, "Jussiape" },
                    { 458, "Caraguataí" },
                    { 459, "Lafaiete Coutinho" },
                    { 460, "Lagoa Real" },
                    { 461, "Laje" },
                    { 462, "Capão" },
                    { 463, "Engenheiro Pontes" },
                    { 464, "Lajedão" },
                    { 465, "Lajedinho" },
                    { 466, "Lajedo do Tabocal" },
                    { 456, "Jussari" },
                    { 467, "Lamarão" },
                    { 469, "Lauro de Freitas" },
                    { 470, "Lençóis" },
                    { 471, "Afrânio Peixoto" },
                    { 472, "Coronel Octaviano Alves" },
                    { 473, "Licínio de Almeida" },
                    { 474, "Tauape" },
                    { 475, "Livramento de Nossa Senhora" },
                    { 476, "Iguatemi" },
                    { 477, "Itanagé" },
                    { 478, "São Timóteo" },
                    { 468, "Lapão" },
                    { 455, "Recife" },
                    { 454, "Queimada Nova" },
                    { 453, "Jussara" },
                    { 430, "Jequié" },
                    { 431, "Baixão" },
                    { 432, "Boaçu" },
                    { 433, "Florestal" },
                    { 434, "Itaibó" },
                    { 435, "Itajuru" },
                    { 436, "Monte Branco" },
                    { 437, "Oriente Novo" },
                    { 438, "Jeremoabo" },
                    { 439, "Canché" },
                    { 440, "Jiquiriçá" },
                    { 441, "Jitaúna" },
                    { 442, "João Dourado" },
                    { 443, "Juazeiro" },
                    { 444, "Abóbora" },
                    { 445, "Carnaíba do Sertão" },
                    { 446, "Itamotinga" },
                    { 447, "Junco" },
                    { 448, "Juremal" },
                    { 449, "Massaroca" },
                    { 450, "Pinhões" },
                    { 451, "Maniçoba" },
                    { 452, "Jucuruçu" },
                    { 479, "Luís Eduardo Magalhães" },
                    { 480, "Macajuba" },
                    { 481, "Nova Cruz" },
                    { 482, "Santa Luzia" },
                    { 510, "Piabanha" },
                    { 511, "Marcionílio Souza" },
                    { 512, "Juraci" },
                    { 513, "Mascote" },
                    { 514, "Pimenta" },
                    { 515, "São João do Paraíso" },
                    { 516, "Teixeira do Progresso" },
                    { 517, "Mata de São João" },
                    { 518, "Açu da Torre" },
                    { 519, "Amado Bahia" },
                    { 520, "Matina" },
                    { 521, "Medeiros Neto" },
                    { 522, "Itupeva" },
                    { 523, "Nova Lídice" },
                    { 524, "Miguel Calmon" },
                    { 525, "Itapura" },
                    { 526, "Tapiranga" },
                    { 527, "Milagres" },
                    { 528, "Tartaruga" },
                    { 529, "Mirangaba" },
                    { 530, "Nuguaçu" },
                    { 531, "Canabrava" },
                    { 532, "Taquarandi" },
                    { 509, "Ibiaçu" },
                    { 534, "Monte Santo" },
                    { 508, "Maraú" },
                    { 506, "Nagé" },
                    { 483, "Macarani" },
                    { 484, "Macaúbas" },
                    { 485, "Canatiba" },
                    { 486, "Lagoa Clara" },
                    { 487, "Macururé" },
                    { 488, "Madre de Deus" },
                    { 489, "Maetinga" },
                    { 490, "Maiquinique" },
                    { 491, "Mairi" },
                    { 492, "Angico" },
                    { 493, "Malhada" },
                    { 494, "Canabrava" },
                    { 495, "Parateca" },
                    { 496, "Malhada de Pedras" },
                    { 497, "Manoel Vitorino" },
                    { 498, "Catingal" },
                    { 499, "Mansidão" },
                    { 500, "Aroeiras" },
                    { 501, "Maracás" },
                    { 502, "Maragogipe" },
                    { 503, "Coqueiros" },
                    { 504, "Guaí" },
                    { 505, "Guapira" },
                    { 507, "São Roque do Paraguaçu" },
                    { 429, "Mangue Seco" },
                    { 641, "Trancoso" },
                    { 643, "Gurupá Mirim" },
                    { 778, "Camurugi" },
                    { 779, "Tapiramutá" },
                    { 780, "Volta Grande" },
                    { 781, "Teixeira de Freitas" },
                    { 782, "Cachoeira do Mato" },
                    { 783, "Teodoro Sampaio" },
                    { 784, "Buracica" },
                    { 785, "Lustosa" },
                    { 786, "Teofilândia" },
                    { 787, "Teolândia" },
                    { 777, "Taperoá" },
                    { 788, "Terra Nova" },
                    { 790, "Rio Fundo" },
                    { 791, "Tremedal" },
                    { 792, "Lagoa Preta" },
                    { 793, "Tucano" },
                    { 794, "Rua Nova" },
                    { 795, "Uauá" },
                    { 796, "Caldeirão" },
                    { 797, "Serra da Canabrava" },
                    { 798, "Ubaíra" },
                    { 799, "Baixinha" },
                    { 789, "Jacu" },
                    { 776, "Tanquinho" },
                    { 775, "Tanque Novo" },
                    { 774, "Sussuarana" },
                    { 751, "Sento Sé" },
                    { 752, "Amaniú" },
                    { 753, "Américo Alves" },
                    { 754, "Piçarrão" },
                    { 755, "Cajuí" },
                    { 756, "Minas do Mimoso" },
                    { 757, "Piri" },
                    { 758, "Serra do Ramalho" },
                    { 759, "Serra Dourada" },
                    { 760, "Serra Preta" },
                    { 761, "Serrinha" },
                    { 762, "Serrolândia" },
                    { 763, "Simões Filho" },
                    { 764, "Sítio do Mato" },
                    { 765, "Gameleira da Lapa" },
                    { 766, "Sítio do Quinto" },
                    { 767, "Sobradinho" },
                    { 768, "Souto Soares" },
                    { 769, "Cisterna" },
                    { 770, "Segrêdo" },
                    { 771, "Tabocas do Brejo Velho" },
                    { 772, "Mariquita" },
                    { 773, "Tanhaçu" },
                    { 800, "Engenheiro Franca" },
                    { 801, "Ubaitaba" },
                    { 802, "Faisqueira" },
                    { 803, "Piraúna" },
                    { 831, "Taboleiro do Castro" },
                    { 832, "Vera Cruz" },
                    { 833, "Cacha Pregos" },
                    { 834, "Jiribatuba" },
                    { 835, "Mar Grande" },
                    { 836, "Vereda" },
                    { 837, "Vitória da Conquista" },
                    { 838, "Bate-Pé" },
                    { 839, "Cabeceira da Jiboia" },
                    { 840, "Cercadinho" },
                    { 841, "Dantilândia" },
                    { 842, "Iguá" },
                    { 843, "Inhobim" },
                    { 844, "José Gonçalves" },
                    { 845, "Pradoso" },
                    { 846, "São João da Vitória" },
                    { 847, "São Sebastião" },
                    { 848, "Veredinha" },
                    { 849, "Wagner" },
                    { 850, "Wanderley" },
                    { 851, "Wenceslau Guimarães" },
                    { 852, "Xique-Xique" },
                    { 853, "Copixaba" },
                    { 830, "Varzedo" },
                    { 750, "Tijuaçu" },
                    { 829, "Várzea Nova" },
                    { 827, "Várzea da Roça" },
                    { 804, "Ubatã" },
                    { 805, "Uibaí" },
                    { 806, "Hidrolândia" },
                    { 807, "Umburanas" },
                    { 808, "Delfino" },
                    { 809, "Una" },
                    { 810, "Colônia" },
                    { 811, "Comandatuba" },
                    { 812, "Pedras de Una" },
                    { 813, "Vila Brasil" },
                    { 814, "Urandi" },
                    { 815, "Uruçuca" },
                    { 816, "Serra Grande" },
                    { 817, "Utinga" },
                    { 818, "Riachão do Utinga" },
                    { 819, "Valença" },
                    { 820, "Guaibim" },
                    { 821, "Guerém" },
                    { 822, "Maricoabo" },
                    { 823, "Serra Grande" },
                    { 824, "Valente" },
                    { 825, "Valilândia" },
                    { 826, "Santa Rita de Cássia" },
                    { 828, "Várzea do Poço" },
                    { 642, "Potiraguá" },
                    { 749, "Igara" },
                    { 747, "Senhor do Bonfim" },
                    { 671, "Ribeirão do Largo" },
                    { 672, "Nova Brasília" },
                    { 673, "Rio de Contas" },
                    { 674, "Arapiranga" },
                    { 675, "Marcolino Moura" },
                    { 676, "Rio do Antônio" },
                    { 677, "Ibitira" },
                    { 678, "Rio do Pires" },
                    { 679, "Ibiajara" },
                    { 680, "Rio Real" },
                    { 670, "Ribeira do Pombal" },
                    { 681, "Rodelas" },
                    { 683, "Morro das Flores" },
                    { 684, "Tapiraípe" },
                    { 685, "Salinas da Margarida" },
                    { 686, "Salvador" },
                    { 687, "Santa Bárbara" },
                    { 688, "Santa Brígida" },
                    { 689, "Santa Cruz Cabrália" },
                    { 690, "Santa Cruz da Vitória" },
                    { 691, "Santa Inês" },
                    { 692, "Santa Luzia" },
                    { 682, "Ruy Barbosa" },
                    { 669, "Ribeira do Amparo" },
                    { 668, "Botuquara" },
                    { 667, "Riacho de Santana" },
                    { 644, "Prado" },
                    { 645, "Cumuruxatiba" },
                    { 646, "Presidente Dutra" },
                    { 647, "Campo Formoso" },
                    { 648, "Presidente Jânio Quadros" },
                    { 649, "Presidente Tancredo Neves" },
                    { 650, "Queimadas" },
                    { 651, "Coronel João Borges" },
                    { 652, "Quijingue" },
                    { 653, "Algodões" },
                    { 654, "Quixabeira" },
                    { 655, "Rafael Jambeiro" },
                    { 656, "Argoim" },
                    { 657, "Cajueiro" },
                    { 658, "Paraguassú" },
                    { 659, "Remanso" },
                    { 660, "Poços" },
                    { 661, "Retirolândia" },
                    { 662, "Riachão das Neves" },
                    { 663, "Cariparé" },
                    { 664, "São José do Rio Grande" },
                    { 665, "Riachão do Jacuípe" },
                    { 666, "Barreiros" },
                    { 693, "Santa Maria da Vitória" },
                    { 694, "Açudina" },
                    { 695, "Inhaúmas" },
                    { 696, "Santa Rita de Cássia" },
                    { 724, "São Gonçalo dos Campos" },
                    { 725, "Afligidos" },
                    { 726, "Sergi" },
                    { 727, "São José da Vitória" },
                    { 728, "São José do Jacuípe" },
                    { 729, "Itatiaia do Alto Bonito" },
                    { 730, "São Miguel das Matas" },
                    { 731, "São Sebastião do Passé" },
                    { 732, "Maracangalha" },
                    { 733, "Jacuípe" },
                    { 734, "Lamarão do Passé" },
                    { 735, "Sapeaçu" },
                    { 736, "Baixa do Palmeira" },
                    { 737, "Sátiro Dias" },
                    { 738, "Saubara" },
                    { 739, "Bom Jesus dos Pobres" },
                    { 740, "Cabuçu" },
                    { 741, "Saúde" },
                    { 742, "Seabra" },
                    { 743, "Baraúnas" },
                    { 744, "Várzea do Caldas" },
                    { 745, "Sebastião Laranjeiras" },
                    { 746, "Mandiroba" },
                    { 723, "Gameleira do Jacaré" },
                    { 748, "Carrapichel" },
                    { 722, "São Gabriel" },
                    { 720, "Mataripe" },
                    { 697, "Malhada Grande" },
                    { 698, "Santa Terezinha" },
                    { 699, "Santaluz" },
                    { 700, "Pereira" },
                    { 701, "Santana" },
                    { 702, "Porto Novo" },
                    { 703, "Santanópolis" },
                    { 704, "Boa Espera" },
                    { 705, "Santo Amaro" },
                    { 706, "Acupe" },
                    { 707, "Campinhos" },
                    { 708, "Santo Antônio de Jesus" },
                    { 709, "Santo Estêvão" },
                    { 710, "São Desidério" },
                    { 711, "Sítio Grande" },
                    { 712, "São Domingos" },
                    { 713, "Santo Antônio" },
                    { 714, "São Felipe" },
                    { 715, "Caraípe" },
                    { 716, "São Félix" },
                    { 717, "Outeiro Redondo" },
                    { 718, "São Félix do Coribe" },
                    { 719, "São Francisco do Conde" },
                    { 721, "Monte Recôncavo" },
                    { 854, "Iguira" },
                    { 428, "Itanhi" },
                    { 426, "Jandaíra" },
                    { 136, "Monte Gordo" },
                    { 137, "Camamu" },
                    { 138, "Barcelos do Sul" },
                    { 139, "Tapuia" },
                    { 140, "Campo Alegre de Lourdes" },
                    { 141, "Peixe" },
                    { 142, "Campo Formoso" },
                    { 143, "Laje dos Negros" },
                    { 144, "Canápolis" },
                    { 145, "Canarana" },
                    { 135, "Abrantes" },
                    { 146, "Paz de Salobro" },
                    { 148, "Ouricana" },
                    { 149, "Poxim do Sul" },
                    { 150, "Candeal" },
                    { 151, "Candeias" },
                    { 152, "Caboto" },
                    { 153, "Caroba" },
                    { 154, "Madeira" },
                    { 155, "Menino Jesus" },
                    { 156, "Passagem dos Teixeiras" },
                    { 157, "Passé" },
                    { 147, "Canavieiras" },
                    { 134, "Camaçari" },
                    { 133, "São João do Panelinha" },
                    { 132, "Camacan" },
                    { 109, "Caatiba" },
                    { 110, "Cabaceiras do Paraguaçu" },
                    { 111, "Geolândia" },
                    { 112, "Cachoeira" },
                    { 113, "Belém da Cachoeira" },
                    { 114, "Santiago do Iguape" },
                    { 115, "Caculé" },
                    { 116, "Caém" },
                    { 117, "Caetanos" },
                    { 118, "Alegre" },
                    { 119, "Caldeirão" },
                    { 120, "Caetité" },
                    { 121, "Brejinho das Ametistas" },
                    { 122, "Caldeiras" },
                    { 123, "Maniaçu" },
                    { 124, "Pajeú do Vento" },
                    { 125, "Cafarnaum" },
                    { 126, "Canal" },
                    { 127, "Cairu" },
                    { 128, "Galeão" },
                    { 129, "Gamboa" },
                    { 130, "Velha Boipeba" },
                    { 131, "Caldeirão Grande" },
                    { 158, "Candiba" },
                    { 159, "Pilões" },
                    { 160, "Cândido Sales" },
                    { 161, "Lagoa Grande" },
                    { 189, "Sítio Novo" },
                    { 190, "Caturama" },
                    { 191, "Central" },
                    { 192, "Chorrochó" },
                    { 193, "Cícero Dantas" },
                    { 194, "São João da Fortaleza" },
                    { 195, "Cipó" },
                    { 196, "Coaraci" },
                    { 197, "Itamotinga" },
                    { 198, "São Roque" },
                    { 199, "Cocos" },
                    { 200, "Conceição da Feira" },
                    { 201, "Conceição do Almeida" },
                    { 202, "Comércio" },
                    { 203, "Rio da Dona" },
                    { 204, "Conceição do Coité" },
                    { 205, "Bandiaçu" },
                    { 206, "Joazeiro" },
                    { 207, "São João" },
                    { 208, "Salgadália" },
                    { 209, "Aroeira" },
                    { 210, "Conceição do Jacuípe" },
                    { 211, "Conde" },
                    { 188, "Bela Flor" },
                    { 108, "Buritirama" },
                    { 187, "Catu" },
                    { 185, "Sítio do Meio" },
                    { 162, "Quaraçu" },
                    { 163, "Cansanção" },
                    { 164, "Canudos" },
                    { 165, "Bedengó" },
                    { 166, "Capela do Alto Alegre" },
                    { 167, "Capim Grosso" },
                    { 168, "Caraíbas" },
                    { 169, "Vila Mariana" },
                    { 170, "Caravelas" },
                    { 171, "Juerana" },
                    { 172, "Ponta da Areia" },
                    { 173, "Santo Antônio de Barcelona" },
                    { 174, "Cardeal da Silva" },
                    { 175, "Carinhanha" },
                    { 176, "Barra da Parateca" },
                    { 177, "Casa Nova" },
                    { 178, "Bem-Bom" },
                    { 179, "Luís Viana" },
                    { 180, "Pau a Pique" },
                    { 181, "Sobrado" },
                    { 182, "Castro Alves" },
                    { 183, "Crussai" },
                    { 184, "Petim" },
                    { 186, "Catolândia" },
                    { 212, "Condeúba" },
                    { 107, "Buerarema" },
                    { 105, "Itaquaraí" },
                    { 29, "Andaraí" },
                    { 30, "Igatu" },
                    { 31, "Ubiraitá" },
                    { 32, "Andorinha" },
                    { 33, "Sítio da Baraúna" },
                    { 34, "Tanquinho do Poço" },
                    { 35, "Angical" },
                    { 36, "Missão de Aricobé" },
                    { 37, "Anguera" },
                    { 38, "Antas" },
                    { 28, "Coquinhos" },
                    { 39, "Antônio Cardoso" },
                    { 41, "Poço" },
                    { 42, "Santo Estevão Velho" },
                    { 43, "Antônio Gonçalves" },
                    { 44, "Aporá" },
                    { 45, "Itamira" },
                    { 46, "Apuarema" },
                    { 47, "Araçás" },
                    { 48, "Aracatu" },
                    { 49, "Araci" },
                    { 50, "Aramari" },
                    { 40, "Oleiro" },
                    { 27, "Anagé" },
                    { 26, "Soares" },
                    { 25, "Prevenido" },
                    { 2, "Catolés" },
                    { 3, "Abaré" },
                    { 4, "Ibó" },
                    { 5, "Acajutiba" },
                    { 6, "Adustina" },
                    { 7, "Água Fria" },
                    { 8, "Pataíba" },
                    { 9, "Aiquara" },
                    { 10, "Alagoinhas" },
                    { 11, "Boa União" },
                    { 12, "Riacho da Guia" },
                    { 13, "Alcobaça" },
                    { 14, "São José" },
                    { 15, "Almadina" },
                    { 16, "Amargosa" },
                    { 17, "Corta Mão" },
                    { 18, "Diógenes Sampaio" },
                    { 19, "Itachama" },
                    { 20, "Amélia Rodrigues" },
                    { 21, "Inhatá" },
                    { 22, "Mata da Aliança" },
                    { 23, "América Dourada" },
                    { 24, "Belo Campo" },
                    { 51, "Arataca" },
                    { 52, "Itatingui" },
                    { 53, "Aratuípe" },
                    { 54, "Maragogipinho" },
                    { 82, "Belo Campo" },
                    { 83, "Biritinga" },
                    { 84, "Boa Nova" },
                    { 85, "Boa Vista do Tupim" },
                    { 86, "Brejo Novo" },
                    { 87, "Bom Jesus da Lapa" },
                    { 88, "Favelândia" },
                    { 89, "Formoso" },
                    { 90, "Bom Jesus da Serra" },
                    { 91, "Água Bela" },
                    { 92, "Boninal" },
                    { 93, "Bastião" },
                    { 94, "Bonito" },
                    { 95, "Boquira" },
                    { 96, "Bucuituba" },
                    { 97, "Botuporã" },
                    { 98, "Brejões" },
                    { 99, "Brejolândia" },
                    { 100, "Brotas de Macaúbas" },
                    { 101, "Ouricuri do Ouro" },
                    { 102, "Saudável" },
                    { 103, "Brumado" },
                    { 104, "Cristalândia" },
                    { 81, "Mogiquiçaba" },
                    { 106, "Ubiraçaba" },
                    { 80, "Boca do Córrego" },
                    { 78, "Barrocas" },
                    { 55, "Aurelino Leal" },
                    { 56, "Laje do Banco" },
                    { 57, "Poço Central" },
                    { 58, "Baianópolis" },
                    { 59, "Várzeas" },
                    { 60, "Baixa Grande" },
                    { 61, "Banzaê" },
                    { 62, "Barra" },
                    { 63, "Ibiraba" },
                    { 64, "Igarité" },
                    { 65, "Barra da Estiva" },
                    { 66, "Triunfo do Sincorá" },
                    { 67, "Barra do Choça" },
                    { 68, "Barra Nova" },
                    { 69, "Barra do Mendes" },
                    { 70, "Antari" },
                    { 71, "Minas do Espírito Santo" },
                    { 72, "Barra do Rocha" },
                    { 73, "Barreiras" },
                    { 74, "Barro Alto" },
                    { 75, "Lagoa do Boi" },
                    { 76, "Lagoa Funda" },
                    { 77, "Barro Preto" },
                    { 79, "Belmonte" },
                    { 427, "Abadia" },
                    { 213, "Alegre" },
                    { 215, "Caraibuna" },
                    { 350, "Iramaia" },
                    { 351, "Novo Acre" },
                    { 352, "Iraquara" },
                    { 353, "Iraporanga" },
                    { 354, "Irará" },
                    { 355, "Bento Simões" },
                    { 356, "Irecê" },
                    { 357, "Angical" },
                    { 358, "Conquista" },
                    { 359, "Itapicuru" },
                    { 349, "Irajuba" },
                    { 360, "Itabela" },
                    { 362, "Itabuna" },
                    { 363, "Itacaré" },
                    { 364, "Taboquinhas" },
                    { 365, "Itaeté" },
                    { 366, "Itagi" },
                    { 367, "Itagibá" },
                    { 368, "Japomirim" },
                    { 369, "Itagimirim" },
                    { 370, "Itaguaçu da Bahia" },
                    { 371, "Itaju do Colônia" },
                    { 361, "Itaberaba" },
                    { 348, "Ibipetum" },
                    { 347, "Ipupiara" },
                    { 346, "Malhador" },
                    { 323, "Boa Vista do Lagamar" },
                    { 324, "Ichu" },
                    { 325, "Igaporã" },
                    { 326, "Igrapiúna" },
                    { 327, "Iguaí" },
                    { 328, "Iguaibi" },
                    { 329, "Ilhéus" },
                    { 330, "Aritaguá" },
                    { 331, "Banco Central" },
                    { 332, "Castelo Novo" },
                    { 333, "Coutos" },
                    { 334, "Inema" },
                    { 335, "Japu" },
                    { 336, "Olivença" },
                    { 337, "Pimenteira" },
                    { 338, "Banco do Pedro" },
                    { 339, "Sambaituba" },
                    { 340, "Inhambupe" },
                    { 341, "Ipecaetá" },
                    { 342, "Cavunge" },
                    { 343, "Ipiaú" },
                    { 344, "Ipirá" },
                    { 345, "Bonfim de Ipirá" },
                    { 372, "Palmira" },
                    { 373, "Itajuípe" },
                    { 374, "Bandeira do Almada" },
                    { 375, "Itamaraju" },
                    { 403, "Ituaçu" },
                    { 404, "Tranqueiras" },
                    { 405, "Ituberá" },
                    { 406, "Iuiu" },
                    { 407, "Jaborandi" },
                    { 408, "Jacaraci" },
                    { 409, "Irundiara" },
                    { 410, "Paiol" },
                    { 411, "Jacobina" },
                    { 412, "Caatinga do Moura" },
                    { 413, "Itaitu" },
                    { 414, "Itapeipu" },
                    { 415, "Junco" },
                    { 416, "Jaguaquara" },
                    { 417, "Ipiúna" },
                    { 418, "Jaguarari" },
                    { 419, "Pilar" },
                    { 420, "Juacema" },
                    { 421, "Jaguaripe" },
                    { 422, "Camassandi" },
                    { 423, "Cunhangi" },
                    { 424, "Jacuruna" },
                    { 425, "Pirajuia" },
                    { 402, "Rio do Meio" },
                    { 322, "Ibotirama" },
                    { 401, "Itati" },
                    { 399, "Itiúba" },
                    { 376, "Itamari" },
                    { 377, "Itambé" },
                    { 378, "Catolezinho" },
                    { 379, "São José do Colônia" },
                    { 380, "Itanagra" },
                    { 381, "Itanhém" },
                    { 382, "Batinga" },
                    { 383, "Ibirajá" },
                    { 384, "Itaparica" },
                    { 385, "Itapé" },
                    { 386, "Itapebi" },
                    { 387, "Caiubi" },
                    { 388, "Itapetinga" },
                    { 389, "Bandeira do Colônia" },
                    { 390, "Itapicuru" },
                    { 391, "Sambaíba" },
                    { 392, "Lagoa Redonda" },
                    { 393, "Itapitanga" },
                    { 394, "Itaquara" },
                    { 395, "Itarantim" },
                    { 396, "Ribeirão do Salto" },
                    { 397, "Itatim" },
                    { 398, "Itiruçu" },
                    { 400, "Itororó" },
                    { 214, "Contendas do Sincorá" },
                    { 321, "Feira Nova" },
                    { 319, "Ibititá" },
                    { 243, "Elísio Medrado" },
                    { 244, "Monte Cruzeiro" },
                    { 245, "Encruzilhada" },
                    { 246, "Vila do Cafe" },
                    { 247, "Entre Rios" },
                    { 248, "Ibatuí" },
                    { 249, "Subaúma" },
                    { 250, "Érico Cardoso" },
                    { 251, "Esplanada" },
                    { 252, "Palame" },
                    { 242, "Dom Macedo Costa" },
                    { 253, "São José do Mucambo" },
                    { 255, "Aribicé" },
                    { 256, "Caimbé" },
                    { 257, "Massacará" },
                    { 258, "Eunápolis" },
                    { 259, "Fátima" },
                    { 260, "Feira da Mata" },
                    { 261, "Ramalho" },
                    { 262, "Feira de Santana" },
                    { 263, "Bonfim da Feira" },
                    { 264, "Humildes" },
                    { 254, "Euclides da Cunha" },
                    { 241, "Dom Basílio" },
                    { 240, "Dias d\"Ávila" },
                    { 239, "Dário Meira" },
                    { 216, "Coração de Maria" },
                    { 217, "Itacava" },
                    { 218, "Retiro" },
                    { 219, "Cordeiros" },
                    { 220, "Coribe" },
                    { 221, "Descoberto" },
                    { 222, "Coronel João Sá" },
                    { 223, "Correntina" },
                    { 224, "São Manoel do Norte" },
                    { 225, "Rosário" },
                    { 226, "Cotegipe" },
                    { 227, "Jupaguá" },
                    { 228, "Taguá" },
                    { 229, "Cravolândia" },
                    { 230, "Crisópolis" },
                    { 231, "Buril" },
                    { 232, "Cristópolis" },
                    { 233, "Cruz das Almas" },
                    { 234, "Curaçá" },
                    { 235, "Barro Vermelho" },
                    { 236, "Patamuté" },
                    { 237, "Poço de Fora" },
                    { 238, "Riacho Seco" },
                    { 265, "Governador Dr. João Durval Carneiro" },
                    { 266, "Jaguara" },
                    { 267, "Jaíba" },
                    { 268, "Maria Quitéria" },
                    { 296, "Iaçu" },
                    { 297, "João Amaro" },
                    { 298, "Lajedo Alto" },
                    { 299, "Ibiassucê" },
                    { 300, "Ibicaraí" },
                    { 301, "Ibicoara" },
                    { 302, "Cascavel" },
                    { 303, "Ibicuí" },
                    { 304, "Água Doce" },
                    { 305, "Ibitupã" },
                    { 306, "Ibipeba" },
                    { 307, "Iguitu" },
                    { 308, "Lagoa Grande" },
                    { 309, "Mirorós" },
                    { 310, "Ibipitanga" },
                    { 311, "Ibiquera" },
                    { 312, "Ibirapitanga" },
                    { 313, "Ibirapuã" },
                    { 314, "Ibirataia" },
                    { 315, "Algodão" },
                    { 316, "Ibitiara" },
                    { 317, "Mocambo" },
                    { 318, "Olhos d\"Água do Seco" },
                    { 295, "Heliópolis" },
                    { 320, "Canoão" },
                    { 294, "Buranhém" },
                    { 292, "Mutãs" },
                    { 269, "Matinha" },
                    { 270, "Tiquaruçu" },
                    { 271, "Filadélfia" },
                    { 272, "Firmino Alves" },
                    { 273, "Itaiá" },
                    { 274, "Floresta Azul" },
                    { 275, "Formosa do Rio Preto" },
                    { 276, "Gandu" },
                    { 277, "Gavião" },
                    { 278, "Gentio do Ouro" },
                    { 279, "Gameleira do Assuruá" },
                    { 280, "Ibitunane" },
                    { 281, "Itajubaquara" },
                    { 282, "Pituba" },
                    { 283, "Santo Inácio" },
                    { 284, "Glória" },
                    { 285, "Gongogi" },
                    { 286, "Tapirama" },
                    { 287, "Governador Mangabeira" },
                    { 288, "Guajeru" },
                    { 289, "Guanambi" },
                    { 290, "Ceraíma" },
                    { 291, "Morrinhos" },
                    { 293, "Guaratinga" }
                });

            migrationBuilder.InsertData(
                table: "Usuarios",
                columns: new[] { "Id", "CPF", "CidadeId", "Discriminator", "NomeCompleto", "Senha", "NomeUF", "VerbaEstadual" },
                values: new object[] { 2147483646, "admin", null, "UFAdmin", "Rui Costa", "admin", "Bahia", 1.7976931348623157E+308 });

            migrationBuilder.CreateIndex(
                name: "IX_Ocorrencias_IntervencaoId",
                table: "Ocorrencias",
                column: "IntervencaoId");

            migrationBuilder.CreateIndex(
                name: "IX_Ocorrencias_PrefeituraId",
                table: "Ocorrencias",
                column: "PrefeituraId");

            migrationBuilder.CreateIndex(
                name: "IX_Ocorrencias_UsuarioId",
                table: "Ocorrencias",
                column: "UsuarioId");

            migrationBuilder.CreateIndex(
                name: "IX_Requisicao_PrefeituraId",
                table: "Requisicao",
                column: "PrefeituraId");

            migrationBuilder.CreateIndex(
                name: "IX_Requisicao_UFAdminId",
                table: "Requisicao",
                column: "UFAdminId");

            migrationBuilder.CreateIndex(
                name: "IX_Usuarios_IntervencaoId",
                table: "Usuarios",
                column: "IntervencaoId");

            migrationBuilder.CreateIndex(
                name: "IX_Usuarios_SetorId",
                table: "Usuarios",
                column: "SetorId");

            migrationBuilder.CreateIndex(
                name: "IX_Usuarios_UFId",
                table: "Usuarios",
                column: "UFId");

            migrationBuilder.CreateIndex(
                name: "IX_Usuarios_PrefeituraId",
                table: "Usuarios",
                column: "PrefeituraId");

            migrationBuilder.CreateIndex(
                name: "IX_Usuarios_CidadeId",
                table: "Usuarios",
                column: "CidadeId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Ocorrencias");

            migrationBuilder.DropTable(
                name: "Requisicao");

            migrationBuilder.DropTable(
                name: "Usuarios");

            migrationBuilder.DropTable(
                name: "Intervencao");

            migrationBuilder.DropTable(
                name: "Cidades");
        }
    }
}
