// <auto-generated />
using System;
using AppMinhaBahia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppMinhaBahia.Migrations
{
    [DbContext(typeof(AppMinhaBahiaContext))]
    partial class AppMinhaBahiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AppMinhaBahia.Models.Intervencao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Intervencao");
                });

            modelBuilder.Entity("AppMinhaBahia.Models.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double?>("Custo")
                        .HasColumnType("double");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("Funcionarios")
                        .HasColumnType("int");

                    b.Property<int>("IntervencaoId")
                        .HasColumnType("int");

                    b.Property<string>("LocalEspecifico")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PrefeituraId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IntervencaoId");

                    b.HasIndex("PrefeituraId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ocorrencia");
                });

            modelBuilder.Entity("AppMinhaBahia.Models.Requisicao", b =>
                {
                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.Property<int>("PrefeituraId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("Funcionarios")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double?>("Verba")
                        .HasColumnType("double");

                    b.HasKey("SetorId", "PrefeituraId");

                    b.HasIndex("PrefeituraId");

                    b.ToTable("Requisicao");
                });

            modelBuilder.Entity("AppMinhaBahia.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("NomeCidade")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");
                });

            modelBuilder.Entity("AppMinhaBahia.Models.Funcionario", b =>
                {
                    b.HasBaseType("AppMinhaBahia.Models.Usuario");

                    b.Property<bool>("Disponivel")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IntervencaoId")
                        .HasColumnType("int");

                    b.Property<int>("SetorId")
                        .HasColumnType("int");

                    b.HasIndex("IntervencaoId");

                    b.HasIndex("SetorId");

                    b.HasDiscriminator().HasValue("Funcionario");
                });

            modelBuilder.Entity("AppMinhaBahia.Models.Prefeitura", b =>
                {
                    b.HasBaseType("AppMinhaBahia.Models.Usuario");

                    b.Property<double>("SalarioMedioPorFuncionario")
                        .HasColumnType("double");

                    b.Property<double>("VerbaEstadual")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("Prefeitura");
                });

            modelBuilder.Entity("AppMinhaBahia.Models.Setor", b =>
                {
                    b.HasBaseType("AppMinhaBahia.Models.Usuario");

                    b.Property<string>("NomeSetor")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PrefeituraId")
                        .HasColumnType("int");

                    b.Property<double>("Verba")
                        .HasColumnType("double");

                    b.HasIndex("PrefeituraId");

                    b.HasDiscriminator().HasValue("Setor");
                });

            modelBuilder.Entity("AppMinhaBahia.Models.Ocorrencia", b =>
                {
                    b.HasOne("AppMinhaBahia.Models.Intervencao", "Intervencao")
                        .WithMany()
                        .HasForeignKey("IntervencaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppMinhaBahia.Models.Prefeitura", "Prefeitura")
                        .WithMany()
                        .HasForeignKey("PrefeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppMinhaBahia.Models.Usuario", "Usuario")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppMinhaBahia.Models.Requisicao", b =>
                {
                    b.HasOne("AppMinhaBahia.Models.Prefeitura", "Prefeitura")
                        .WithMany("Requisicoes")
                        .HasForeignKey("PrefeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppMinhaBahia.Models.Setor", "Setor")
                        .WithMany("Requisicoes")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppMinhaBahia.Models.Funcionario", b =>
                {
                    b.HasOne("AppMinhaBahia.Models.Intervencao", "Intervencao")
                        .WithMany("FuncionariosAlocados")
                        .HasForeignKey("IntervencaoId");

                    b.HasOne("AppMinhaBahia.Models.Setor", "Setor")
                        .WithMany("Funcionarios")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppMinhaBahia.Models.Setor", b =>
                {
                    b.HasOne("AppMinhaBahia.Models.Prefeitura", "Prefeitura")
                        .WithMany("Setores")
                        .HasForeignKey("PrefeituraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
